# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-instrumentation-rails', '~> 0.36.0'
gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.1'
gem 'rails', '~> 8.0.2'
gem 'sqlite3', '~> 2.0'
gem 'uptrace', '~> 1.11'
